export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  COMPTABLE = 'COMPTABLE',
  LOGISTICIEN = 'LOGISTICIEN',
  COMMERCIAL = 'COMMERCIAL',
  VENDEUR = 'VENDEUR',
}
