/**
 * Base de connaissances de l'assistant "mode d'emploi" — HORS LIGNE.
 * Chaque entrée : question, mots-clés (synonymes inclus), réponse en étapes,
 * et éventuellement un lien vers la page concernée.
 */
export interface HelpEntry {
  id: string
  cat: string
  q: string
  keywords: string
  steps: string[]
  route?: string
  routeLabel?: string
  note?: string
}

export const CATEGORIES = [
  'Démarrage',
  'Abonnés',
  'Encaissement',
  'Paramétrage',
  'Crédit & Finances',
  'Service abonnement',
  'Logistique',
  'Analyses',
  'Système',
  'Définitions',
] as const

export const HELP_KB: HelpEntry[] = [
  // ---------------- Démarrage ----------------
  { id: 'connexion', cat: 'Démarrage', q: 'Comment se connecter ?',
    keywords: 'connexion connecter login mot de passe identifiant entrer acceder ouvrir session demarrer lancer',
    steps: ['Ouvre le navigateur sur http://localhost:5173', 'Saisis ton identifiant et ton mot de passe', 'Clique sur « Se connecter ».'] },
  { id: 'deconnexion', cat: 'Démarrage', q: 'Comment me déconnecter ?',
    keywords: 'deconnexion deconnecter quitter sortir fermer session logout',
    steps: ['Clique sur tes initiales en bas à gauche', 'Clique sur « Déconnexion ».'] },
  { id: 'motdepasse', cat: 'Démarrage', q: 'J’ai oublié mon mot de passe',
    keywords: 'mot de passe oublie perdu changer reinitialiser reset code secret',
    steps: ['Contacte ton administrateur', 'Il peut recréer ton compte ou réinitialiser ton accès depuis Paramétrage → Comptes.'] },
  { id: 'navigation', cat: 'Démarrage', q: 'Comment me déplacer dans les menus ?',
    keywords: 'menu naviguer deplacer rubrique section page gauche cliquer ouvrir',
    steps: ['Le menu de gauche regroupe toutes les rubriques par thème', 'Clique sur un titre pour le déplier', 'Clique sur une entrée pour ouvrir la page.'] },
  { id: 'theme', cat: 'Démarrage', q: 'Comment passer en mode sombre / clair ?',
    keywords: 'mode sombre clair theme nuit jour couleur ecran lune soleil affichage',
    steps: ['Clique sur l’icône lune/soleil en haut à droite.'] },
  { id: 'notifications', cat: 'Démarrage', q: 'Où sont mes notifications / alertes ?',
    keywords: 'notification alerte cloche rappel message avertissement bandeau',
    steps: ['Clique sur la cloche 🔔 en haut à droite', 'Les bandeaux jaunes en haut de page signalent aussi les points à traiter.'] },

  // ---------------- Abonnés ----------------
  { id: 'creer-abonne', cat: 'Abonnés', q: 'Comment créer / recruter un nouvel abonné ?',
    keywords: 'creer ajouter nouvel nouveau abonne client recruter recrutement inscrire souscription enregistrer saisir',
    steps: ['Menu « Base de données globale »', 'Bouton « + Nouvel abonné »', 'Renseigne nom, prénom, téléphone, formule et PDV (n° généré si vide)', 'Clique « Créer ».'],
    route: '/app/bdd-globale', routeLabel: 'Ouvrir la base des abonnés' },
  { id: 'modifier-abonne', cat: 'Abonnés', q: 'Comment modifier un abonné ?',
    keywords: 'modifier changer corriger editer abonne client information telephone nom',
    steps: ['Menu « Base de données globale »', 'Clique sur la ligne de l’abonné', 'Modifie les champs puis « Enregistrer ».'],
    route: '/app/bdd-globale', routeLabel: 'Ouvrir la base des abonnés' },
  { id: 'resilier-abonne', cat: 'Abonnés', q: 'Comment résilier / supprimer un abonné ?',
    keywords: 'resilier supprimer enlever desactiver retirer abonne client effacer',
    steps: ['Menu « Base de données globale »', 'Clique sur l’icône corbeille de la ligne', 'L’abonné passe en « Résilié » (son historique est conservé).'],
    route: '/app/bdd-globale', routeLabel: 'Ouvrir la base des abonnés' },
  { id: 'voir-abonnes', cat: 'Abonnés', q: 'Où voir tous les abonnés ?',
    keywords: 'voir liste tous abonnes base donnees globale parc clients consulter',
    steps: ['Menu « Base de données globale » : tous les abonnés avec statut et échéance.'],
    route: '/app/bdd-globale', routeLabel: 'Ouvrir la base des abonnés' },
  { id: 'nouveaux-abonnes', cat: 'Abonnés', q: 'Où voir les nouveaux abonnés (bienvenue) ?',
    keywords: 'nouveau nouveaux bienvenue recents recemment recrutes derniers abonnes',
    steps: ['Menu Service Abonnement → « Bienvenue » : la liste des abonnés récemment recrutés.'],
    route: '/app/bienvenue-abonnes', routeLabel: 'Ouvrir Bienvenue' },
  { id: 'nonqual', cat: 'Abonnés', q: 'C’est quoi les abonnés non qualifiés ?',
    keywords: 'non qualifie nq incomplet dossier manquant decodeur telephone vide a completer',
    steps: ['Ce sont les fiches incomplètes (décodeur non attribué ou téléphone manquant)', 'Menu Service Abonnement → « Abonnés non qualifiés » pour les compléter.'],
    route: '/app/abonnes-nonqual', routeLabel: 'Ouvrir les non qualifiés' },

  // ---------------- Encaissement ----------------
  { id: 'encaissement', cat: 'Encaissement', q: 'Comment faire un encaissement / réabonnement ?',
    keywords: 'encaissement encaisser reabonnement reabonner paiement payer recrutement migration operation caisse vendre montant recu enregistrer',
    steps: ['Menu Opérations → « Encaissement »', 'Cherche le client (n° abonné, nom, téléphone ou n° décodeur) et sélectionne-le', 'Choisis le type, la formule, le nombre de mois et le mode de paiement', 'Saisis le montant reçu (la monnaie se calcule seule)', 'Clique « Enregistrer » : l’abonné est réactivé avec sa nouvelle échéance.'],
    route: '/app/encaissement', routeLabel: 'Ouvrir l’encaissement' },
  { id: 'impaye', cat: 'Encaissement', q: 'Comment enregistrer un impayé (paiement partiel) ?',
    keywords: 'impaye impayes dette partiel arriere reste du reglement non paye versement partiel',
    steps: ['Menu Opérations → « Encaissement »', 'Sélectionne le client puis le type « Impayés »', 'Saisis le montant reçu (peut être inférieur au prix)', 'Enregistre : noté SANS prolonger l’abonnement.'],
    route: '/app/encaissement', routeLabel: 'Ouvrir l’encaissement' },
  { id: 'diff-operations', cat: 'Encaissement', q: 'Différence entre recrutement, réabonnement et migration ?',
    keywords: 'difference recrutement reabonnement migration impaye type operation cest quoi',
    steps: ['Recrutement = un NOUVEau client (première souscription)', 'Réabonnement = un client existant qui renouvelle', 'Migration = changement de matériel/formule', 'Impayés = enregistrer un règlement partiel/arriéré.'] },
  { id: 'options-enc', cat: 'Encaissement', q: 'C’est quoi les options Premium / International / Timbre ?',
    keywords: 'option premium international intl timbre supplement chaine ajout encaissement prix',
    steps: ['Ce sont des suppléments payants à cocher lors de l’encaissement', 'Leur montant s’ajoute automatiquement au total.'] },
  { id: 'recu', cat: 'Encaissement', q: 'Comment imprimer le reçu ?',
    keywords: 'recu ticket facture imprimer encaissement preuve justificatif',
    steps: ['Après avoir enregistré un encaissement, le reçu s’affiche', 'Tu peux l’imprimer ou l’enregistrer en PDF.'] },
  { id: 'terrain', cat: 'Encaissement', q: 'Comment encaisser sur le terrain / téléphone ?',
    keywords: 'terrain mobile telephone tablette dehors exterieur vad vue simplifiee',
    steps: ['Sur la page Encaissement, bascule en haut à droite sur « Terrain »', 'Vue simplifiée adaptée au mobile.'],
    route: '/app/encaissement', routeLabel: 'Ouvrir l’encaissement' },
  { id: 'champs-comp', cat: 'Encaissement', q: 'Où saisir le n° de contrat et la date de RDV ?',
    keywords: 'numero contrat date rdv rendez vous prochain telephone 2 date paiement champ complementaire',
    steps: ['Sur la page Encaissement, en bas de « Détails de l’opération »', 'Section « Informations complémentaires » : N° contrat, Tél 2, Date prochain RDV, Date de paiement.'],
    route: '/app/encaissement', routeLabel: 'Ouvrir l’encaissement' },

  // ---------------- Paramétrage ----------------
  { id: 'creer-pdv', cat: 'Paramétrage', q: 'Comment créer un point de vente (PDV) ?',
    keywords: 'creer pdv point de vente boutique agence sous reseau partenaire ajouter magasin nouveau',
    steps: ['Menu Paramétrage → « Liste PDV »', 'Bouton « Nouveau »', 'Renseigne code, raison sociale, type, secteur, localité, caution', 'Enregistre.'],
    route: '/app/pdv-liste', routeLabel: 'Ouvrir la liste des PDV' },
  { id: 'formule', cat: 'Paramétrage', q: 'Comment ajouter ou modifier une formule ?',
    keywords: 'formule offre abonnement prix tarif access evasion prestige ajouter modifier creer catalogue essentiel tout canal',
    steps: ['Menu Paramétrage → « Formules »', 'Bouton « Nouveau » (ou clique une ligne pour modifier)', 'Renseigne code, nom, prix matériel et prix formule', 'Enregistre.'],
    route: '/app/formules', routeLabel: 'Ouvrir les formules' },
  { id: 'baremes', cat: 'Paramétrage', q: 'Comment changer les barèmes de commission ?',
    keywords: 'bareme baremes commission taux pourcentage 3500 8475 g11 materiel formule reabo modifier valeur calcul',
    steps: ['Menu Paramétrage → « Barèmes commissions »', 'Modifie les valeurs (matériel, formule %, réabo %, G11)', 'Clique « Sauvegarder » : tous les calculs se mettent à jour.'],
    route: '/app/baremes', routeLabel: 'Ouvrir les barèmes' },
  { id: 'obj-dist', cat: 'Paramétrage', q: 'Comment fixer les objectifs du distributeur ?',
    keywords: 'objectif distributeur global cible but annee trimestre mois effectif fixer saisir',
    steps: ['Menu Paramétrage → « Objectifs Distributeur »', 'Renseigne année, trimestre/mois, formule, type et effectif', 'Ajoute l’objectif.'],
    route: '/app/objectifs-distributeur', routeLabel: 'Ouvrir les objectifs distributeur' },
  { id: 'obj-pdv', cat: 'Paramétrage', q: 'Comment fixer / importer les objectifs par PDV ?',
    keywords: 'objectif pdv point vente cible import csv excel charger mois effectif fixer',
    steps: ['Menu Paramétrage → « Objectifs PDV »', 'Saisis un objectif (PDV, mois, type, effectif) OU clique « Importer CSV »', 'Format CSV : code_pdv, annee, mois, type, effectif.'],
    route: '/app/objectifs-pdv', routeLabel: 'Ouvrir les objectifs PDV' },
  { id: 'banques', cat: 'Paramétrage', q: 'Comment gérer les banques ?',
    keywords: 'banque compte bancaire wave orange money ajouter creer mobile money',
    steps: ['Menu Paramétrage → « Banques »', 'Ajoute ou modifie un compte (nom, n° compte, type).'],
    route: '/app/banques', routeLabel: 'Ouvrir les banques' },
  { id: 'localites', cat: 'Paramétrage', q: 'Comment gérer les localités et secteurs ?',
    keywords: 'localite secteur zone ville region quartier geographie ajouter',
    steps: ['Menu Paramétrage → « Localités » pour les localités (rattachées à un secteur).'],
    route: '/app/localites', routeLabel: 'Ouvrir les localités' },
  { id: 'entrepots', cat: 'Paramétrage', q: 'Comment gérer les entrepôts ?',
    keywords: 'entrepot magasin stock depot capacite ajouter principal secondaire',
    steps: ['Menu Paramétrage → « Entrepôts »', 'Ajoute ou modifie un entrepôt (code, nom, type, capacité).'],
    route: '/app/entrepot', routeLabel: 'Ouvrir les entrepôts' },
  { id: 'comptes', cat: 'Paramétrage', q: 'Comment créer un compte utilisateur (vendeur, etc.) ?',
    keywords: 'utilisateur compte vendeur agent role acces creer personnel employe mot de passe comptes ajouter',
    steps: ['Menu Paramétrage → « Comptes PDV » (ou Comptes Distributeur)', 'Crée le compte et choisis son rôle', 'Chaque rôle ne voit que ce qui le concerne.'],
    route: '/app/pdv-comptes', routeLabel: 'Ouvrir les comptes' },
  { id: 'roles', cat: 'Paramétrage', q: 'C’est quoi les rôles (admin, manager, vendeur…) ?',
    keywords: 'role droit acces permission admin manager comptable logisticien commercial vendeur qui voit quoi',
    steps: ['Chaque utilisateur a un rôle qui détermine ce qu’il voit', 'Admin/Manager = tout ; Comptable = finances ; Logisticien = stock ; Commercial/Vendeur = ventes et abonnés.'] },

  // ---------------- Crédit & Finances ----------------
  { id: 'dettes', cat: 'Crédit & Finances', q: 'Où voir les dettes / le crédit des PDV ?',
    keywords: 'dette dettes credit recouvrement encours solde du impaye plafond avoir rapport qui doit argent',
    steps: ['Gestion Crédit → « Suivi Crédit » : plafond, avoir, dette, crédit dispo par PDV', 'Gestion Crédit → « Rapport dette » : uniquement ceux qui doivent.'],
    route: '/app/rapport-dette', routeLabel: 'Ouvrir le rapport dette' },
  { id: 'caution', cat: 'Crédit & Finances', q: 'Comment augmenter la caution d’un PDV ?',
    keywords: 'caution augmentation augmenter garantie depot pdv increase',
    steps: ['Menu Opérations → « Augmentation Caution »', 'Sélectionne le PDV, le montant et la date, puis enregistre.'],
    route: '/app/augmentation-caution', routeLabel: 'Ouvrir l’augmentation de caution' },
  { id: 'arrete', cat: 'Crédit & Finances', q: 'C’est quoi un arrêté de solde ?',
    keywords: 'arrete solde fige figer cloture periode pdv comptable',
    steps: ['C’est figer le solde d’un PDV à une date donnée', 'Menu Opérations → « Arrêtés Soldes ».'],
    route: '/app/arretes-soldes', routeLabel: 'Ouvrir les arrêtés' },
  { id: 'versement', cat: 'Crédit & Finances', q: 'Comment enregistrer / valider un versement en banque ?',
    keywords: 'versement banque bordereau valider rejeter depot argent caisse encaisse',
    steps: ['Menu Opérations → « Versement Banque »', 'Ajoute : PDV, montant, banque, date, n° bordereau', 'Valide un versement en attente (réduit la dette) ou rejette avec motif.'],
    route: '/app/versement-banque', routeLabel: 'Ouvrir les versements' },
  { id: 'retrait', cat: 'Crédit & Finances', q: 'Comment gérer un retrait banque ?',
    keywords: 'retrait banque sortie argent retirer compte',
    steps: ['Menu Opérations → « Retrait Banque »', 'Enregistre le retrait (montant, banque, date).'],
    route: '/app/retrait-banque', routeLabel: 'Ouvrir les retraits' },
  { id: 'depenses', cat: 'Crédit & Finances', q: 'Comment enregistrer une dépense ?',
    keywords: 'depense depenses sortie argent frais charge motif justificatif enregistrer',
    steps: ['Menu Opérations → « Dépenses »', 'Bouton « Nouveau »', 'Renseigne date, catégorie, motif, montant et justificatif.'],
    route: '/app/depenses', routeLabel: 'Ouvrir les dépenses' },
  { id: 'matching', cat: 'Crédit & Finances', q: 'C’est quoi le rapprochement (matching) ?',
    keywords: 'matching rapprochement ecart comparer rapport encaissement controle verifier',
    steps: ['Compare les rapports d’activité importés avec les encaissements réels', 'Menu Opérations → « Matching » pour voir les écarts.'],
    route: '/app/matching', routeLabel: 'Ouvrir le matching' },
  { id: 'rapport-activite', cat: 'Crédit & Finances', q: 'Comment importer un rapport d’activité ?',
    keywords: 'rapport activite importer fichier excel charger releve mensuel',
    steps: ['Menu Opérations → « Rapport Activité »', 'Importe le fichier ; les chiffres servent au rapprochement.'],
    route: '/app/rapport-activite', routeLabel: 'Ouvrir les rapports' },

  // ---------------- Service abonnement ----------------
  { id: 'echeance', cat: 'Service abonnement', q: 'Où voir les abonnés à échéance ou échus ?',
    keywords: 'echeance echu expire expiration fin abonnement bientot a echeance aae liste relancer',
    steps: ['« Abonnés à échéance » : ceux qui vont bientôt expirer', '« Échus » : ceux déjà expirés.'],
    route: '/app/aae', routeLabel: 'Ouvrir les abonnés à échéance' },
  { id: 'relance', cat: 'Service abonnement', q: 'Comment relancer les abonnés (SMS) ?',
    keywords: 'relance relancer sms message rappel echeance echu envoyer notifier contacter telephone campagne',
    steps: ['Service Abonnement → « Abonnés à échéance » ou « Échus »', 'Coche les abonnés', 'Clique « Relance SMS » (ou « Exporter les numéros » pour une campagne WhatsApp).'],
    note: 'L’envoi SMS automatique est simulé pour l’instant : utilise « Exporter les numéros » pour envoyer via ton téléphone/WhatsApp en attendant un fournisseur SMS.',
    route: '/app/aae', routeLabel: 'Ouvrir les abonnés à échéance' },
  { id: 'export-num', cat: 'Service abonnement', q: 'Comment récupérer les numéros pour une campagne ?',
    keywords: 'numero telephone exporter liste campagne whatsapp sms groupe contact relance copier',
    steps: ['Sur « Abonnés à échéance », « Échus » ou « Bienvenue »', 'Clique sur « Exporter les numéros »', 'Tu obtiens un fichier Excel des téléphones à utiliser pour ta campagne.'],
    route: '/app/aae', routeLabel: 'Ouvrir les abonnés à échéance' },
  { id: 'suivi-mp', cat: 'Service abonnement', q: 'Comment suivre le réabonnement (M+) ?',
    keywords: 'suivi mp m+ reabonnement cohorte taux conversion m+1 m+2 m+3 fidelisation',
    steps: ['Service Abonnement → « Suivi Réabonnement M+ »', 'Choisis le mois de recrutement, l’année et le niveau (M+1/2/3)', 'Le tableau montre le taux de réabonnement par cohorte.'],
    route: '/app/suivi-mp', routeLabel: 'Ouvrir le Suivi M+' },
  { id: 'reabo-momo', cat: 'Service abonnement', q: 'Où voir les réabonnements Mobile Money (MOMO) ?',
    keywords: 'momo mobile money wave orange money reabonnement liste paiement',
    steps: ['Service Abonnement → « Réabo MOMO » : les réabonnements payés via Wave/Orange Money.'],
    route: '/app/reabo-momo', routeLabel: 'Ouvrir Réabo MOMO' },
  { id: 'rpe', cat: 'Service abonnement', q: 'C’est quoi le Retour client RPE ?',
    keywords: 'rpe retour client appel satisfaction qualite enquete suivi',
    steps: ['Suivi de la qualité des appels et de la satisfaction client', 'Menu Suivi Commercial → « Retour RPE » pour créer/compléter les fiches.'],
    route: '/app/retour-rpe', routeLabel: 'Ouvrir Retour RPE' },

  // ---------------- Logistique ----------------
  { id: 'decodeur', cat: 'Logistique', q: 'Comment retrouver un décodeur ?',
    keywords: 'decodeur recherche numero serie statut stock vendu immobilise z4 globaz g11 materiel trouver',
    steps: ['Menu Logistique → « Recherche décodeur »', 'Saisis le numéro de série', 'La fiche montre le type, le statut et l’emplacement.'],
    route: '/app/recherche-decodeur', routeLabel: 'Ouvrir la recherche décodeur' },
  { id: 'livraison', cat: 'Logistique', q: 'Comment faire une livraison / un mouvement de stock ?',
    keywords: 'livraison mouvement stock transfert envoyer materiel entrepot pdv bon livraison',
    steps: ['Menu Logistique → « Livraison »', 'Crée un mouvement (type, matériel, quantité, n° bon de livraison).'],
    route: '/app/livraison', routeLabel: 'Ouvrir les livraisons' },
  { id: 'immobilises', cat: 'Logistique', q: 'Où voir les décodeurs immobilisés (non sortis) ?',
    keywords: 'immobilise non sorti 3 mois bloque stock dormant ancien decodeur jours',
    steps: ['Menu Logistique → « Décodeurs immobilisés » : ceux en stock depuis plus de 3 mois sans mouvement.'],
    route: '/app/decodeurs-immobilises', routeLabel: 'Ouvrir les immobilisés' },
  { id: 'stock-entrepot', cat: 'Logistique', q: 'Comment consulter le stock d’un entrepôt ?',
    keywords: 'stock entrepot inventaire consulter quantite decodeur disponible',
    steps: ['Menu Logistique → « Consultation Entrepôt » ou « Inventaire Entrepôt ».'],
    route: '/app/consultation-entrepot', routeLabel: 'Ouvrir la consultation entrepôt' },
  { id: 'accessoires', cat: 'Logistique', q: 'Comment gérer / vendre les accessoires ?',
    keywords: 'accessoire vente cable parabole kit stock suivi consultation',
    steps: ['Menu Gestion Accessoires → « Suivi des ventes » et « Consultation ».'],
    route: '/app/acc-suivi-ventes', routeLabel: 'Ouvrir les ventes accessoires' },
  { id: 'vad', cat: 'Logistique', q: 'Comment gérer la VAD (vente à domicile) ?',
    keywords: 'vad vente domicile kit vadeur stock consultation livraison terrain',
    steps: ['Menu Gestion des VAD → « Vente Kit » pour enregistrer une vente', '« Consultation » pour voir le stock VAD.'],
    route: '/app/vad-vente-kit', routeLabel: 'Ouvrir la VAD' },

  // ---------------- Analyses ----------------
  { id: 'ca-pdv', cat: 'Analyses', q: 'Où voir le chiffre d’affaires par PDV ?',
    keywords: 'chiffre affaire ca pdv vente montant performance recette par point de vente',
    steps: ['Menu Analytique → « CA par PDV ».'],
    route: '/app/stat-ca-pdv', routeLabel: 'Ouvrir le CA par PDV' },
  { id: 'classement', cat: 'Analyses', q: 'Où voir le classement des PDV ?',
    keywords: 'classement ranking meilleur performance pdv top podium comparer',
    steps: ['Menu Analytique → « Classement » : les PDV classés par performance.'],
    route: '/app/stat-classement', routeLabel: 'Ouvrir le classement' },
  { id: 'arpu', cat: 'Analyses', q: 'C’est quoi l’ARPU ?',
    keywords: 'arpu revenu moyen abonne par user average revenue indicateur',
    steps: ['ARPU = revenu moyen par abonné actif (CA ÷ parc actif)', 'Menu Analytique → « ARPU ».'],
    route: '/app/arpu', routeLabel: 'Ouvrir l’ARPU' },
  { id: 'rendement-user', cat: 'Analyses', q: 'Où voir le rendement des agents (users) ?',
    keywords: 'rendement user agent vendeur performance recrutement par utilisateur',
    steps: ['Menu Analytique → « Rendement des USERS » / « Recrutement par Formule/User ».'],
    route: '/app/recrut-formule-user', routeLabel: 'Ouvrir le rendement' },
  { id: 'audit', cat: 'Analyses', q: 'Où voir le journal des actions (audit) ?',
    keywords: 'audit journal historique action securite qui a fait quoi trace log',
    steps: ['Menu Analytique → « Récap Audit » : chaque action importante est tracée.'],
    route: '/app/ana-recap-audit', routeLabel: 'Ouvrir le journal' },

  // ---------------- Système ----------------
  { id: 'export', cat: 'Système', q: 'Comment exporter en Excel ou PDF ?',
    keywords: 'export exporter excel pdf imprimer telecharger document fichier sortir tableau',
    steps: ['Ouvre la page contenant le tableau', 'Clique « Excel » ou « PDF » en haut à droite du tableau', 'Le fichier se télécharge.'] },
  { id: 'recherche', cat: 'Système', q: 'Comment rechercher un abonné, un PDV ou un décodeur ?',
    keywords: 'recherche rechercher trouver chercher abonne pdv decodeur barre globale',
    steps: ['Utilise la barre de recherche en haut de l’écran', 'Tape au moins 2 lettres', 'Clique sur un résultat.'] },
  { id: 'sauvegarde', cat: 'Système', q: 'Mes données sont-elles sauvegardées ?',
    keywords: 'sauvegarde sauvegarder backup perdre donnees securite copie restaurer protection',
    steps: ['Oui : sauvegarde automatique au démarrage et chaque jour', 'Les 14 dernières sont dans backend/backups', 'Sauvegarde manuelle : commande « npm run backup ».'] },
  { id: 'maj', cat: 'Système', q: 'Comment mettre à jour le logiciel ?',
    keywords: 'mise a jour mettre jour update nouvelle version bundle telecharger',
    steps: ['Télécharge le nouveau fichier .bundle', 'Double-clique « METTRE-A-JOUR.bat »', 'En ~30 s : nouveautés récupérées, données conservées, redémarrage.'] },
  { id: 'offline', cat: 'Système', q: 'Le logiciel marche-t-il sans internet ?',
    keywords: 'internet hors ligne offline connexion sans reseau wifi marche fonctionne',
    steps: ['Oui : tout le cœur du logiciel marche sans internet (base locale)', 'Seuls les extras (vrais SMS, paiement en ligne, vraie IA) ont besoin d’internet.'] },
  { id: 'vide', cat: 'Système', q: 'Pourquoi les listes / menus sont vides ?',
    keywords: 'vide rien affiche aucun donnee manque pourquoi absent liste formule vide rien ne saffiche',
    steps: ['C’est normal sur une base neuve : le logiciel n’invente aucune donnée', 'Crée d’abord un PDV, puis des abonnés, puis des encaissements', 'Les tableaux se remplissent alors automatiquement.'] },
  { id: 'securite', cat: 'Système', q: 'Le logiciel est-il sécurisé ?',
    keywords: 'securite securise protection mot de passe chiffre role acces confidentiel',
    steps: ['Oui : mots de passe chiffrés, connexion par jeton, rôles par utilisateur, et journal d’audit de toutes les actions.'] },

  // ---------------- Définitions (glossaire) ----------------
  { id: 'def-pdv', cat: 'Définitions', q: 'C’est quoi un PDV ?',
    keywords: 'definition pdv point de vente boutique cest quoi signifie',
    steps: ['PDV = Point De Vente : une boutique, agence ou partenaire de ton réseau de distribution.'] },
  { id: 'def-formule', cat: 'Définitions', q: 'C’est quoi une formule ?',
    keywords: 'definition formule offre bouquet abonnement cest quoi',
    steps: ['Une formule est une offre d’abonnement vendue (ex. ACCESS, EVASION), avec un prix matériel et un prix formule.'] },
  { id: 'def-mp', cat: 'Définitions', q: 'C’est quoi M+1, M+2, M+3 ?',
    keywords: 'definition m+ m+1 m+2 m+3 cohorte reabonnement cest quoi signifie',
    steps: ['C’est le suivi du réabonnement : parmi les clients recrutés un mois donné, combien se réabonnent 1, 2 ou 3 mois après (M+1, M+2, M+3).'] },
  { id: 'def-ro', cat: 'Définitions', q: 'C’est quoi R/O et Atterrissage ?',
    keywords: 'definition r/o ro atterrissage reste realiser objectif cest quoi pourcentage',
    steps: ['R/O = Réalisé ÷ Objectif (en %)', 'Reste à réaliser = Objectif − Réalisé', 'Atterrissage = projection de fin de mois selon le rythme actuel.'] },
  { id: 'def-decodeur', cat: 'Définitions', q: 'C’est quoi Z4, GLOBAZ, G11 ?',
    keywords: 'definition z4 globaz g11 decodeur type materiel cest quoi',
    steps: ['Ce sont les types de décodeurs gérés dans le stock (Z4, GLOBAZ, G11).'] },
  { id: 'def-credit', cat: 'Définitions', q: 'C’est quoi plafond, avoir, dette, encours ?',
    keywords: 'definition plafond avoir dette encours credit cest quoi solde',
    steps: ['Plafond = crédit maximum accordé au PDV', 'Avoir = ce qu’il a en positif', 'Dette / Encours = ce qu’il doit', 'Crédit dispo = Plafond + Avoir − Dette.'] },
]
